lambda_1_values = [...
    0 ...
    0.1 ...
    0.2 ...
    0.3 ...
    0.5 ...
    0.7 ...
    1.1 ...
    1.4 ...
    1.8 ...
    2.3 ...
    2.7 ...
    3.2 ...
    4.0 ...
];

lambda_2_values = [...
    0 ...
    0.2 ...
    0.4 ...
    0.7 ...
    1.1 ...
    1.6 ...
    2.1 ...
    2.7 ...
    3.4 ...
    4.1 ...
    4.7 ...
    5.5 ...
    6.2 ...
];

JJ0 = 0 : 0.1 : 1.2;


wavelengths = {lambda_1_values, lambda_2_values};
titles = {'λ1', 'λ2'};
files = {'ex2_lambda_1.png', 'ex2_lambda_2.png'};

for i = 1:2
    fig = figure('Visible','off');

    plot(JJ0, wavelengths{i}, 'o-');
    
    xlabel('J/J_0'); ylabel('I_ф, мкА'); title(titles{i});
    
    grid on; grid minor;
    
    xticks(JJ0);
    yticks(unique(round(wavelengths{i}, 2)));
    
    saveas(fig, ['results/' files{i}]);
    close(fig);
end
