If = [ ...
    2.7 ...
    4.7 ...
    36.2 ...
    40.9 ...
    52.8 ...
    52.8 ...
    33.0 ...
    0.3 ...
];

lambda = [ ...
    430 ...
    470 ...
    520 ...
    565 ...
    590 ...
    660 ...
    700 ...
    860 ...
];


wavelengths = {If};
titles = {''};
files = {'ex3_spectral.png'};

for i = 1
    fig = figure('Visible','off');

    plot(lambda, wavelengths{i}, 'o-');
    
    xlabel('\lambda'); ylabel('I_ф, мкА'); title(titles{i});
    
    grid on; grid minor;
    
    xticks(lambda);
    yticks(unique(round(wavelengths{i}, 2)));
    
    saveas(fig, ['results/' files{i}]);
    close(fig);
end
