I_phi = [ ...
    2.86 ...
    3.51 ...
    2.08 ...
    1.06 ...
    0.56 ...
    0.26 ...
    0.06 ...
    0.06 ...
];

lambda = [ ...
    430 ...
    470 ...
    520 ...
    565 ...
    590 ...
    660 ...
    700 ...
    860 ...
];

y_axis = {I_phi};
x_axis = lambda;

titles = {'I_{ф.н} = f(\lambda)'};
files = {'ex4.png'};

for i = 1 : length(y_axis)
    fig = figure('Visible','off');

    plot(x_axis, y_axis{i}, 'o-');

    xlabel('\lambda'); ylabel('I_{ф.н}, мкА'); title(titles{i});

    grid on; grid minor;
    
    xticks(x_axis);
    yticks(unique(round(y_axis{i}, 2)));
    
    saveas(fig, ['results/' files{i}]);
    close(fig);
end